### ISSUE TITLE
Update CSS of all pages

### ISSUE THREAD

**Issue by tjhickey724** [tjhickey724/SpecsGradingApp#48]
Look into the pull request which updates all of my CSS!

**Comment by EtchJetty** [comment]
One immediate note for the change: [the Jumbotron class no longer exists in Bootstrap 5.2.X](https://getbootstrap.com/docs/5.2/migration/#jumbotron). Instead, [they](https://getbootstrap.com/docs/5.2/examples/jumbotron/) (and [I, in the change](https://github.com/EtchJetty/SpecsGradingApp/blob/main/views/stats.ejs)) use classes to replicate the class.

**Comment by tjhickey724** [comment]
I've accepted all of the CSS changes!  Nice work, Viridia!
